const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN: 'user/LOGIN',
  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
  LOGOUT: 'user/LOGOUT',
  HANDLE_AUTHENTICATION_CALLBACK: 'user/HANDLE_AUTHENTICATION_CALLBACK',
}

export default actions
